# Generated by Django 2.2.1 on 2019-05-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagegallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='locat',
        ),
    ]
